apiVersion: v1
kind: Secret
metadata:
  name: erasegraph-secrets
  namespace: erasegraph
type: Opaque
stringData:
  POSTGRES_PASSWORD: "erasegraph_secret"
  DB_PASSWORD: "erasegraph_secret"
  RABBITMQ_PASSWORD: "erasegraph_secret"
