apiVersion: v1
kind: Secret
metadata:
  name: erasegraph-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "erasegraph.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  DB_PASSWORD:       {{ .Values.secrets.dbPassword | quote }}
  RABBITMQ_PASSWORD: {{ .Values.secrets.rabbitmqPassword | quote }}
